### ISSUE TITLE
Acquisition monitor (e.g. sum wf between events) 

### ISSUE THREAD

**Issue by tunnell** [XENON1T/pax#204]
I need to implement two things:

Written to raw data  - The acquisition monitor is just a board that we will know from the run db.  The MongoDB untriggered reader plugin should fetch this data outside of the event window.  This will also mean adding to the Event class a field called 'time_to_last_trigger' or equivalent.  This is fine since our coincidence pretrigger runs serially.  This means that every XENON1T event will have raw data outside of the event window that needs to be ignored.  

Any analysis - At the moment, we don't know how we're going to use this data.  It's sort of a smart self-veto cut in some cases.  It also records things like the busy.  After we turn on XENON1T, we'll start finding uses for this information that should be known at the analysis stage.  This should remain possible.

**Comment by JelleAalbers** [comment]
We discussed this briefly at the collaboration meeting. For reference: the acquisition monitor is a separate digitizer which will read out several signals such as a GPS clock or the muon veto trigger. Self-triggering will almost certainly have to be used on it to avoid crazy data rates. For more info, see slide 7 of https://xecluster.lngs.infn.it/dokuwiki/lib/exe/fetch.php?media=xenon:xenon1t:org:collaborationmeeting2016_daq.pdf

To start we could just save the AqM self-triggered pulses, maybe just noting the origin in a more sensible way (i.e. instead of saving "this pulse is from channel 6, module bla" but "this pulse is from the muon veto trigger"). For the sum waveforms there may be a lot of pulses though, then we should think about doing a more advanced reduction.

Since the data stream is decoupled from the pax events, it would make sense to store it in the same way as the trigger data. This will go first to MongoDB (so it can be monitored online), then to a to-be-specified file format (currently hdf5, could also be pickle/json/etc, will not be ROOT).

The actual querying can be done by the event builder or by a completely separate application. We can't just treat them as regular channels, we'll have to do a different query: unlike for TPC pulses we do want to read and save the raw data all the time.
