### ISSUE TITLE
Noise spectra analysis

### ISSUE THREAD

**Issue by coderdj** [XENON1T/pax#205]
The DAQ will take noise runs in the same way it takes LED runs, just without the LED. The raw noise data will be saved like normal runs. In addition we want to explore the idea of some online analysis that would give the shifter instant feedback on the characteristics of the noise for the current run (similar to what is possible now with DAX). 

The noise analysis would be a simple pax plugin that would be run by the trigger whenever the run doc has {"detectors.tpc.trigger.mode": "noise"}. It would output data to the online DB where it can be displayed on the web interface. We can discuss the exact format but something like DAX's histograms of the highest bin in each waveform of each PMT is probably a decent start.

**Comment by JelleAalbers** [comment]
The trigger data will allow continuous dark rate monitoring once it passes through MongoDB. As for noise frequency and amplitude spectra,  is pax really the right place for this? Since this will likely be in very short runs taken before the main run (https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:noise:noise_monitoring_work_page), do we really actually need an online tool?

**Comment by JelleAalbers** [comment]
Let's close this, it seems like a problem for the online/offline monitor, not pax.
