### ISSUE TITLE
Additional information in run doc

### ISSUE THREAD

**Issue by coderdj** [XENON1T/pax#227]
The trigger should probably leave some information in the run doc after it finishes. This would include:

 - Version of trigger used to record run
 - Trigger algorithms included (in case we add more high level conditions)
 - How many valid triggers are contained in the run, maybe also the raw file size.
 - There must be an end condition where a data file is written somewhere. Maybe the trigger should record this location. If there is a handshake with another system this can also be documented in the run doc.
 - Any other useful diagnostics (toss/keep, timestamps, etc). 

Right now the place for most of this would be doc.detectors.tpc.trigger (which is a dict). Though certain information, like the number of events, could also go on the top level.

**Comment by JelleAalbers** [comment]
The trigger's config is now stored in the run doc, as well as some basic statistics (events found, pulses read, signals found, etc), the pax version and the timestamp. The data location and transfer things are  also in the run doc, courtesy of cax. More advanced info about the data (dark rate, signals outside events) is in the trigger data. 

Are there other specific things that should be in the run doc, rather than the trigger data?

**Comment by JelleAalbers** [comment]
... if there are, we can either reopen this or make a new issue.
