### ISSUE TITLE
Output files are sometimes just ".root". Pax should give all files names.

### ISSUE THREAD

**Issue by alecstein** [XENON1T/pax#340]
I was burned for a couple of days looking for a processed file that had the name ".root." When pax processes a dataset in a folder, it could instead create a .root file with the same name as the folder.

**Comment by JelleAalbers** [comment]
As far as I know, this happens only if you add a trailing slash to the `--output_name`, and the output format is not directory-based (e.g. it is WriteROOTClass, not a FolderIO subclass). I think the easiest way to solve this is to disallow trailing slashes for the output_name option altogether. Does this resolve the issue Alec?

**Comment by alecstein** [comment]
Jelle, that's a good call -- it happened to me when I had a trailing slash at the end of the `--input` flag variable. 

It makes sense to me that, if the user does `--input /path/to/dir/` to truncate this to `--input /path/to/dir` (so that the flags are equivalent) rather than disallowing the slash.

**Comment by JelleAalbers** [comment]
That's possible, though it may not do what you expect: if you give `--input /path/to/dir/` you're probably expecting a file `/path/to/dir/somethingnice.root`. If I'd subtract the slash you'd get `/path/to/dir.root` as your output.

**Comment by alecstein** [comment]
Seems like the problem is that `--input ` and `--output` are ambiguous between file and directory. Unless you want to write separate flags for them then I guess it's just a judgment call.

**Comment by pelssers** [comment]
My thoughts on this:

The only unambiguous thing is that a trailing `/` at the end of a pathname forces the pathname to refer to a directory. From [this post](http://unix.stackexchange.com/questions/1910/how-does-linux-handle-multiple-consecutive-path-separators-home-username).
So if you supply `some/path/` to either `--input` or `--output` you are specifying a directory and are saying nothing about a (possible) filename.

I guess with the `--input` flag this behaviour is fine since pax will look for files of the right type in this directory and process them.

For the `--output` option we want pax to produce a single file (with a nice name preferably). So either supply a name: `--output name` and pax will make a file `name.root` in the directory it's running. Or give it a filename including a path: `--output /some/path/name` and get the file `name.root` in the `/some/path/` directory.
This will of course result in the file `.root` if you supply `--output /some/path/` since you give no filename.

So my suggestion is to keep the `--input` option as is and disallow the trailing `/` for `--output` since it will always need a filename.

**Comment by Riciardos** [comment]
You could also do a small check for the trailing slash: if `--output /some/path/` then use the name of the input file. For example : `--input /some/path/inputfile.xed --output /some/other/path/` would give you a inputfile.root in the `/some/other/path/` directory. If the `--input` argument is a directory, it still looks for a first file to begin with and use that as your name.

This way the output file is in the directory you wanted it to be, instead of the previous one.

I do agree that disallowing trailing slashes is probably the easiest solution.

**Comment by tunnell** [comment]
Someone willing to try a solution, make pull request, then we can review?

**Comment by JelleAalbers** [comment]
Since disallowing trailing slashes has fixed the initial issue, I will close this. If anyone is willing to go further and add features like automatic file creation with sensible names inside a chosen directory other than `.` that would be great, you can reference this issue in your pull request.
