### ISSUE TITLE
Proposal to add variable containing total pulse area to Pulse class (if feasible).

### ISSUE THREAD

**Issue by DCichon** [XENON1T/pax#356]
Having such a variable would make certain analyses, like designing a signal-noise cut and selecting pulses which do not contain a valid signal, easier.

**Comment by sanderbreur** [comment]
Do you mean the area of all pulses in one event as a value saved in all
pulses?

Op wo 4 mei 2016 om 17:48 schreef Dominick Cichon <notifications@github.com

**Comment by DCichon** [comment]
The area of a single pulse saved as a parameter of the pulse it belongs to.

**Comment by sanderbreur** [comment]
Ok, just to understand better:

- Instead of using the area of hits you would like to use the area of
pulses?
- For a noise cut wouldn't one use the area's of all hits or peaks?

In any pulse, hits are found if they are above the baseline, would you
expect a lot of area in the parts of the pulse that is not a hit? Well
anyway one can always implement it and see how it compares to area of hits.

Op za 7 mei 2016 om 14:05 schreef Dominick Cichon <notifications@github.com

**Comment by NataschaRupp** [comment]
I also think that a variable for the area of the single pulses in one event is a good idea. I needed the sum of all pulse areas in one event when I had a look at a signal-to-noise cut similar to the one in XENON100, where the AreaTot of the waveform was saved. I think that the sum of the pulse areas is the equivalent to AreaTot and that it can be useful.

**Comment by tunnell** [comment]
pax is better at single electrons and (since no channels removed from S1 finding) lone hits.  Therefore, I think you'll get arguably a better variable than AreaTot by just doing sum(peaks.area) for peaks not in interaction (i.e. not main S1 or main S2).  In principle, these should be very similar since the signal-noise cut is just 'remove events with so much garbage on waveform that it can't be WIMP'.  @sanderbreur saw some wacky events in XENON1T already that could be cut with such a cut.  Also, @famaro77 has made a tool that can help you compare a pax-ified cut to the old XeRawDP cut.  The signal processors work differently so the cuts may need to be adapted.

(I'm still not back.. well, I'm still on beach.  Just wanted to chime in to make sure things stay clear)

**Comment by tunnell** [comment]
Reopen if active request
