### ISSUE TITLE
Crash when multi-processing filter box datasets

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#390]
Runs 1060-1063 (filter box tests) fail during multiprocess due to memory issue, even when increasing mem_per_cpu to 4 GB from standard 2 GB.

Using XENON1T_LED config. Description of runs from Dominick:

> This could be caused by having about 1k events with a window length of 1 ms without any data reduction (i.e. self triggering or ZLE)

Example log file:
```
/project/lgrandi/xenon1t/processing/160622_1412_v5.0.0/160622_1412_v5.0.0_19088665.log
```

Files process successfully with single process, 2 GB.

**Comment by JelleAalbers** [comment]
Thanks for reporting. I think this is due to the maximum queue size: up to 1000 events are allowed to sit in the queue waiting to be processed and/or written to output by default. Could you check if it processes if you add the paxer argument  `--config_string [pax]event_block_size=1`? We can make this the default setting in LED mode if it works.

**Comment by JelleAalbers** [comment]
@pdeperio would you like to see any further action based on this?
