### ISSUE TITLE
EndOfFile error in trigger

### ISSUE THREAD

**Issue by tunnell** [XENON1T/pax#394]
We got an EndOfFile error in the trigger:

https://gist.github.com/tunnell/9e536aa3762ac8c99a74e031c20d0e59

This line on MongoDB.py, line 296:

   `times, modules, channels, areas = future.result()`

Lead to this:

`monary.monary.MonaryError: b'End of file'`

No clue why.  Resulted in DAQ stopping.

**Comment by JelleAalbers** [comment]
I followed the rabbit trail a little, the error is raised [here](https://bitbucket.org/djcbeach/monary/src/5b0fb0c2de0a4f4b32bd79bb593e8cf2f39fe474/monary/monary.py?at=default&fileviewer=file-view-default#monary.py-702) when -1 is returned from [here](https://bitbucket.org/djcbeach/monary/src/5b0fb0c2de0a4f4b32bd79bb593e8cf2f39fe474/monary/cmonary.c?at=default&fileviewer=file-view-default#cmonary.c-1043). This indicates a MongoDB cursor failure, see [here](http://api.mongodb.com/c/1.2.3/cursors.html). While mongo passes along a message what the cursor error is, Monary discards this (because it's calling a C function which is only allowed to return an integer). Perhaps the cursor error is traceable somewhere in the mongo logs?

**Comment by tunnell** [comment]
Let's see if comes back.
