### ISSUE TITLE
Dead time calculation is nonsense

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#416]
~~Right now the dead time is only computed for each individual system (just the time between X-on and X-off signals).~~

**Comment by sanderbreur** [comment]
I just checked what we report as the dead time of a channel by using:
hax.trigger_data.get_trigger_data(run_number, 'dead_time_info')['busy']

This gives back:
85.6075 minutes of information (308187 'one second blocks') which should just be ~60 minutes. 

If we plot it we see there are negative dead times:

![cjesahwci64aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/6515893/18628337/04dfb18a-7e60-11e6-8e31-cb41c197ab83.png)

Which is confirmed by looking into the one second blocks with negative dead time:
block of one 1 | dead time in one s
563       -149.251286
16655     -834.618663
23109     -986.833308
36617    -1243.150632
43161    -1351.905806
47347    -1416.232646
48784    -1436.585358
112618   -2189.314070
119312   -2253.597712
166196   -2661.853579
185424   -2810.000000
199808   -2919.566562
233338   -3155.000007
246175   -3241.662968
259353   -3327.115389
300956   -3584.771966

Zooming into the positive region we see:

![6acgmiywmfl98mma0chkiyw4cqmpkngx6zb2zm9tib2ncx2xyktsp snaamv8vzmysf3xk38zmnilji4hsib8v5c8b6ghz0vrmcdoqqvbyfjozaxbn38zmzmysrxkyj5mzmzlzi3jn38zmzmysrbmzb2zmzmbwotzznzmzmznrue7sm5mzmzm1khf2zczmzmxa1p8bfoj23hilxo8aaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/6515893/18628343/0c01147c-7e60-11e6-9cf3-8ac0a61094f8.png)


Which shows that there are 'positive dead times', most one second long and more happen at the start then at the end.

Right now we cannot use the sum of dead time to get a good value for the deadtime of the run and thus we cannot say anything about the absolute rate. For Kr and Rn analysis this is a problem.

**Comment by JelleAalbers** [comment]
Thanks for looking into this Sander, this is indeed an important issue. Looks like the output from the trigger data is just nonsense you can't use at all. There are probably bugs in the trigger algorithm for determining the dead time: it's rather awful code I wrote in a hurry at some point. 

However, there may be a problem or two in a system before the trigger: I occasionally get two busy-on signals or two busy-off signals in a row, which I don't think should happen. I think this is something someone on the pax side and someone on the daq side will have to debug together.

**Comment by buetikofer** [comment]
Thanks for pointing this out. No, two busy-on or busy-off signals in a row should clearly not happen. Sounds like a bug in the v1495 firmware. I'll have to look into this.

**Comment by buetikofer** [comment]
I updated the firmware of the v1495. With this update the problem should be solved. 

The start and stop signals are 50 ns wide most of the time. But occasionally they are only 25 ns (these are probably the signals that have been missed previously). I hope this is not a problem for processing/interpreting these channels in pax. 

does someone already have a notebook to check acquisition monitor output? just to check if bug is fixed.

**Comment by JelleAalbers** [comment]
25 or 50 ns is fine; the trigger just looks to see if there is any pulse; ao as long as it passes the self-trigger threshold of the acquisition monitor its ok. You can see if there are still double busy-on or busy-off pulses by checking the event builder log (in raw data folder of each run, eventbuilder.log) for warnings.

**Comment by sanderbreur** [comment]
Ok, I just checked two of the latest processed datasets and this is what I find:

Quick conclusions:
- The negative numbers are gone.
- All time stamps of a zero busy are ok
- Off all time stamps of a non zero busy are either correct or are just '1.0s'
- If I assume every second a measurement is taken then there are way more measurements point than  expected
- The total dead time could be correct (but I actually do not know how cross check that)

To get the data I am using:
dead_times = np.array(hax.trigger_data.get_trigger_data(run_number, 'dead_time_info')['time'])
busy_triggers = np.array(hax.trigger_data.get_trigger_data(run_number, 'dead_time_info')['busy'])

For RUN 3318 (2016/10/03 11:06:28):
Just the first 10 entries:
Length of busy [s] |  Timestamp [s]
0 1.0
0 2.0
0 3.0
0 4.0
0 5.0
0 6.0
0 7.0
0 8.0
0 9.0
0 10.0

That looks good, but If I now only select the values where the busy_triggers >0 I get the following which should be time ordered....

Length of busy [s] |  Timestamp [s]
0.0071089 12.0
0.02283463 1.0
0.00431633 37.0
0.00458823 1.0
0.02967531 1.0
0.02009826 1.0
0.00591525 1.0
0.01401143 154.0
0.03670691 1.0
0.02236412 177.0

So some times the time is correct or it gives back 1s (1e9 ns).
Plotting this gives:
![pcaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/6515893/19074800/4af27cb4-8a42-11e6-9dd8-4bd85dc30bb3.png)

We see way to many points around 1.

If I instead of using the times just take the index we get this:

![hyscfv7mgvd1aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/6515893/19074831/7eb7b898-8a42-11e6-9997-8ea4f0b45e19.png)

Is the assumption correct that we take one value every second? Because then I would expect this plot to go till 3600 and not >2e5... in time

We can compare with the next dataset: 3319 (2016/10/03 12:06:43) In this dataset the anode was turned off after ~ 15 minutes, So we should see a drop in busy signals after 1/4th of the lenth of the dataset.

![tiaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/6515893/19074958/0fd51eb0-8a43-11e6-840e-f7a1ac727020.png)

![a2hxsheyopw1aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/6515893/19074963/12d257fe-8a43-11e6-82a3-d2893e771f64.png)

So we do see that the busy is only found in the first part of the dataset as expected. But now again the index is not representive of the total time...

This is what I can find, I rather leave the debugging now for Jelle who knows the trigger code best.

**Comment by JelleAalbers** [comment]
On the one-minute run I checked this looks good now. `hax.trigger_data.get_trigger_data` has been updated. @sanderbreur could you repeat your checks.

**Comment by JelleAalbers** [comment]
I've looked at several of the radon runs where the DAQ was busy a lot of the time; the dead time calculation seems quite reasonable:

![deadtime](https://cloud.githubusercontent.com/assets/4354311/19278465/92b03974-8fdd-11e6-824d-8b3770498883.png)

I don't believe the first bar,; but that's probably something unrelated, there were several DAQ problems when the radon was at its highest rate.

In background runs the dead time is usually very small, which is also reasonable. Since Sander is on shift and may not be able to have a look soon, I'm going to assume this is resolved unless proven otherwise :-).
