### ISSUE TITLE
Better event display peak label hiding

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#423]
Currently the event display shows the labels of all peaks in the waveform. However, many of our events have a large single electron tail; if each of these are labeled, an ominous black cloud forms:

![000009](https://cloud.githubusercontent.com/assets/4354311/18554789/a5012502-7b65-11e6-9ec9-3b06ea74d716.png)

It would be nice if we labeled only the largest few peaks, or do something smarter to label a maximum number of peaks per few us. There is already an option `hide_peak_info` you can add in the `Plotting` section to not show any peak labels.

**Comment by JelleAalbers** [comment]
Addressed in #427

**Comment by JelleAalbers** [comment]
Sander and I tried the fix in #427 a few weeks ago, but nothing happened. Maybe we did something wrong though, we or someone should probably check again.

**Comment by JelleAalbers** [comment]
We don't know if this is fixed yet

**Comment by Riciardos** [comment]
I have taken a look at it and for me it seems to be working for me on the XENON100 file in the data folder. You just have to include in the XENON100.ini file in the [Plotting] section a num_of_sections variable and an annotation_filter list like:
`[Plotting]`
`num_of_sections = 40`
`annotation_filter = ['largest']`
(it should work the same in the XENON1T config file)
Instead of `['largest']`, you can also try `['largest_s1s', 'largest_s2s']`, so it will filter the types separately (so you won't miss an s1 sitting right next to an s2).

Also, I can understand if having to edit the config file every time could be a bit cumbersome, so I can also try to make it so you can override it with a command line option like: `--annotation_filter ['largest', 5]` to include the largest 5 S1s and largest 5 S2s.

I will create a separate working branch so you can check out if it's still not working for you.

**Comment by Riciardos** [comment]
There is a branch 'annotation_filter_working' with how it's working for me, so check that one out and see if it's working for you as well (I also cleaned up a print statement and a comment). Only thing I've added was the ['largest'] list to the annotation_filter variable in _base.ini

**Comment by Riciardos** [comment]
There is a branch 'annotation_filter_working' with how it's working for me, so check that one out and see if it's working for you as well (I also cleaned up a print statement and a comment). Only thing I've added was the ['largest'] list to the annotation_filter variable in _base.ini
