### ISSUE TITLE
Trigger should report trigger rate

### ISSUE THREAD

**Issue by coderdj** [XENON1T/pax#424]
There should be some record of the trigger rate reported to the DAQ frontend and also stored in historian. We could be taking a ton of data but not making triggers. This is important to know.

This could be fleshed out with other diagnostic information if needed. The toss/keep ratio, for example, is definitely interesting.

**Comment by JelleAalbers** [comment]
Hi Dan,

#420 will report the events built per 21 second block to the trigger monitor database, in docs with `data_type="batch_info"`. Some other basic information, such as the total length of the events, is also included. 

Toss/keep in terms of time can be easily derived from this (total length / event built). As for toss/keep in terms of pulses, I'm not sure how to do this without introducing another expensive loop over pulses. The problem is that the event decision gets made at the end of the trigger, when pulses have already been abstracted to signals. 

After #422 / #425 toss/keep in terms of pulses can be derived; take the the number of pulses read from the trigger monitor data (or the run doc), and the number of pulses per event from (a sample of) events in the processed data (e.g. your online monitor).

**Comment by coderdj** [comment]
Thanks, 21 second granularity is enough. We basically just want to know if the trigger crashed and burned or if there was some sudden, massive change to the event rate. I might use the existence of these docs as a sort of heartbeat for the trigger.

Toss/keep over time is enough, we just want a very general idea of how much of the x MB/s the readers are pumping into mongo is actually getting saved. I think if we start stressing this thing with calibration runs having some live diagnostics of this will help us choose settings that maximize the final event rate. 

For me this solves the issue. But maybe we should wait to close it until those PRs are merged?
