### ISSUE TITLE
Implementation of S2 broadening in FAX

### ISSUE THREAD

**Issue by ErikHogenbirk** [XENON1T/pax#476]
(Disclaimer: I am looking into some simulated data, so will probably make a few issues here. Let me know if this is not the right place, but we need to keep track of fax improvements somewhere, right?)

The S2 broadening observed in simulated data does not follow the trend found in data. Here I show two plots: one of AmBe data, one with simulated AmBe data, both superimposed with [https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:drift_and_diffusion](Jelle's model) 

Real data:
![s2broadening_data](https://cloud.githubusercontent.com/assets/9975649/21891992/93396ffa-d8d5-11e6-91c1-58f25396ef73.PNG)

Simulation:
![s2broadening_sim](https://cloud.githubusercontent.com/assets/9975649/21891993/9339b514-d8d5-11e6-90c9-162a02ff14a5.PNG)

It seems to me that Jelle's diffusion model is pretty good, perhaps we can use this in fax until we have done a full study?

**Comment by JelleAalbers** [comment]
We are already using my diffusion model in pax (sort of), except that the width at zero depth is not an explicit parameter, but arises naturally through simulating single electrons. I'm surprised you get such high widths at low depths, the single electron model should be much narrower... not sure what's going on

**Comment by mcfatelin** [comment]
@ErikHogenbirk Can you please specify what configuration (version) of fax you were using for getting the simulated S2 width verse z you obtained as the second plot?

Because Joey has presented a note last week: https://xecluster.lngs.infn.it/dokuwiki/lib/exe/fetch.php?media=xenon:xenon1t:sim:notes:jhowlett:preliminary_fax_only_studies_170131.html, showing that W/WO PMT after pulse enabled in simulation, the s2 width shows a great difference. And WO PMT after pulse it looks like more compatible with data. 

@JelleAalbers Do you think it possible that in your model of S2 shape (https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:single_electron_waveform_shape) that the PMT after pulse is counted? So that by putting again the PMT after pulse in fax, we actually are double-counting the PMT after pulse effect in terms of S2 width.

**Comment by ErikHogenbirk** [comment]
@mcfatelin MC version 0.1.2, pax version 6.2.1. I have some new simulation data available (mc 0.1.7, pax 6.2.1) which I will start analyzing soon.

**Comment by pdeperio** [comment]
This issue was moved to XENON1T/mc#30
