### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '^_'.

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#519]
Get this error when processing some old runs like ```1172``` (not sure if it's cax problem configuring pax):
```
_pickle.UnpicklingError: invalid load key, '^_'.
```
in log:
```
/project/lgrandi/xenon1t/cax/1172_v6.4.1/1172_v6.4.1_24151623.log
```

**Comment by JelleAalbers** [comment]
These runs are in a different format (zipped BSON rather than zipped Pickle). There used to be runs db entries telling pax to use the correct input plugin, but they got lost a few months ago during a bugged electron lifetime update.

Could you move this issue over to cax? I guess you could either get the information on which run used what format from a runs db backup, or test each run individually and determine the format from that.

**Comment by pdeperio** [comment]
This issue was moved to XENON1T/cax#82
