### ISSUE TITLE
Can we simulate a middle finger?

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#547]
From [the waveform watching campaign](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:firstresults:waveform_watching), a few S2s that really don't want us to succeed:

![s2](https://cloud.githubusercontent.com/assets/8642192/23685467/cd09cba8-0369-11e7-8404-423007eba8ad.png)

(thanks @Murra for the categorization)

**Comment by pdeperio** [comment]
can be closed if we find a simulated event that matches, or if some weird issue with hit grouping...

**Comment by feigaodm** [comment]
I think I have seen such a simulated WF, but could find it. I resimulated 8 WFs and find 1 double finger structure. I think this structure is due to randomness in the diffusion process. Will close the issue. But can reopen if you don't agree :)

![screen shot 2017-07-18 at 4 49 35 pm](https://user-images.githubusercontent.com/18223253/28339224-6281f3c2-6bd9-11e7-8201-3ab096221a14.png)
