### ISSUE TITLE
Request for peak area calculated based on summed waveform 

### ISSUE THREAD

**Issue by mcfatelin** [XENON1T/pax#559]
Looks like the peak area in current pax version is the sum of all the hit area. According to the [analysis of signal bias](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:mcfate:non-linearity_z_dependence), there seems to be a bias coming from the baseline calculation of each hit. It will be better if we could add another variable of peak area which is calculated based on summed gain-corrected waveform:

1. For comparing with hit-based area to study the signal bias
2. Provide more options in analysis.

**Comment by JelleAalbers** [comment]
Hi Qing, the sum waveform is the sum of all hit waveforms, so this should give the same answer (except when peaks are overlapping). Even the raw sum waveform (which includes the noise samples the digitizers take left and right of each hit) would be affected if there is baseline corrected, as you can't sum PMT waveforms before baselining. 

We could compute another sum waveform where only the reference baseline (16000) is subtracted from each pulse, but then you're putting a lot of faith in the baseline computed on the readers at the beginning of the run.

Do you have any indication a baselining problem is the cause of this bias? I would suspect the bias comes rather from not being able to detect low-amplitude (<15 ADC counts) hit due to the self-trigger threshold. During dense/large signals, hits pile up so small hits start sitting on top of larger hits, and pass the self-trigger threshold that way. In small/sparse signals this doesn't happen, so their area is slightly reduced.

There may be some indication of this effect: the mean area/hit in single electrons is 1.3-1.4, larger than we'd expect from the ~16% estimated double pe emission. See e.g. https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:single_electron_gain_stability#results figure 6 and https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:double_pe_emission (done when we had incorrect PMT gains, so mean area/hit is actually smaller than 1 in this study). There is some hit pile-up even in single electrons (only on the top array), which could also partially explain the high area/hit.

**Comment by mcfatelin** [comment]
Hi Jelle,
Sorry for not being clear. My proposal was trying to solve two issues.


1) First what I proposed is more variables for each peak to cross check about the area calculated based on different baselines. I agree with you that hit-loss due to self-trigger threshold or hit finding threshold is definitely one cause of the signal bias. But as we already saw from [the signal bias study](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:mcfate:non-linearity_z_dependence) (Fig.4), it doesn't explain the signal bias difference between pax v6.2.1 and v6.4.2, and the positive bias since we always lose hits due to ZLE and hit finding inefficiency. 

That's why it seems to me it indicated another component beside ZLE which is responsible for the signal bias. And since pax v6.4.2 greatly reduces the signal bias's drift time dependence, and it shall be a hit level change (See Fig.6 of [the note](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:mcfate:non-linearity_z_dependence)), I suppose the baseline calculation change in the [pull request](https://github.com/XENON1T/pax/pull/479) made the change. 

Then if the previous improvement is due to the baseline calculation, it could still has some effect in current version. The baseline is calculated as the average of pre-samples in each pulse. But average can be easily biased by small contamination in the pulse pre-windows. Median or mod may be better in this case. So I think adding more area variables will help tracing the source of signal bias, and the analysis. Especially the area with different baseline calculation method (median or mod). 

I was thinking maybe each peak has multiple pulses in each channel, and each pulse has individual baseline. If baseline is biased, having an universal baseline for each channel may help. But it seems each pulse has at least 1us window, so ma be this is not so relevant to the signal bias we saw.

2) And for the summed waveform, I wasn't saying sum before baselining. It is mainly for including the hits that were not picked up by hit finder. This, I think, will reduce the effect you also mentioned about hit loss.

Sorry if you already have the note previously debugging this kind of issue, please point me to the notes.

**Comment by feigaodm** [comment]
Tried to implement sth to check this s2 linearity problem due to peak finding threshold. Here is a branch I generated. https://github.com/XENON1T/pax/commit/1c4892b96480cf7dd5e5a8bf69052797a1e9c341

So what I did is try to integral everything in the pulse that contribute to the s2 peak (do not require that a raw adc count is above hit_finder threshold). After this modification, the new intergrated s2 area very similar to the default one (difference at o(0.1%) level ). According to @mcfatelin , this can not account for the electron lifetime issue.
