### ISSUE TITLE
S1 patterns map

### ISSUE THREAD

**Issue by l-althueser** [XENON1T/pax#653]
I observed a (huge) difference between the interpolated and directly extracted S1 patterns maps while generating the new S1 patterns from MC v2.1.0 + geo update (see PR). The generation notebook that shows the different binning and the extraction process is [here on GitHub](https://github.com/XENON1T/MCAnalysisScripts/blob/master/PerPMT_LCE_Time/Xe1T_MC_perPMT.ipynb).

The interpolation (introduced by someone in the past - maybe Jelle?) uses {nbins_r = 5, nbins_phi = [4,6,8,12,12], nbins_z = 60} as data source and interpolates to xyz (23,23,60). I have also extracted the LCE values for the xyz binning directly which yields to the following comparison:

![unbenannt](https://user-images.githubusercontent.com/13698969/34184276-189a3e26-e51f-11e7-8f4b-ab65530a4999.png)

The difference plot has a `vmin` and `vmax` on it. The LCE values are directly from the maps and are normalized within PAX/FAX.

See also section `Tests of the maps` in the [notebook](https://github.com/XENON1T/MCAnalysisScripts/blob/master/PerPMT_LCE_Time/Xe1T_MC_perPMT.ipynb) for S1 LCE maps for all PMTs with and without interpolation.

- Do we want not interpolated maps in PAX?
- Should I replace the bins outside the TPC with the closest value inside the TPC then?
- Will this have any impact on something except FAX?

**Comment by JelleAalbers** [comment]
Thanks for looking at the S1 Pattern maps! Besides fax, these are used for the S1 pattern fit and for the (currently unused) hitpattern-based saturation correction. 

If I understand you correctly, both top plots show the photon detection efficiency of PMT 187 sliced at x=0. The difference is in how the map was generated from the MC hitpatterns:
 1. Left: Binned with a fine (x, y, z) Cartesian binning
 2. Right: Binned with a coarse (r, phi, z) binning. Then, since PatternFitter requires a regular/Cartesian map, use the InterpolateAndExtrapolate to generate the map for use in pax.

The first XENON1T LCE maps (from Fabio) also had Cartesian binning (https://github.com/XENON1T/pax/pull/302). Later @pdeperio made new maps using polar binning (https://github.com/XENON1T/pax/pull/488), which you updated (https://github.com/XENON1T/pax/pull/577). In #654 I assume you're going back to Cartesian binning?

I would guess statistics is more important than the choice of binning. Certainly Cartesian binning is easier, especially since the end target is a Cartesian map, so it avoids the extra interpolation step. It will be more accurate than polar binning near the bottom array, where proximity to the PMT is the main factor. Maybe higher up in the TPC, the proximity of the wall becomes more important, which polar binning is better at quantifying. I guess this + support for limited statistics (at some point I think we considered taking these from real data) is why Patrick chose radial binning for the previous maps. 

I can't really judge the significance of the differences from these plots: the top plots have a very large color range (set by the out-of-TPC points) while the bottom point has a very small scale (0.01%). It looks like there are quite a few statistical artifacts. Did you check the new maps are smooth in the fiducial volume even with the new binning? A log color scale plot may be useful. Maybe you already have this in one of your notes though.

**Comment by tunnell** [comment]
@l-althueser can we close?
